/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ThreeTriangles;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        LocateCamera lc = new LocateCamera();
        
        lc.addLandmark(new LocateCamera.LandMark(new LocateCamera.Point(65, 175), 0));
        lc.addLandmark(new LocateCamera.LandMark(new LocateCamera.Point(0, 200), 1)); 
        lc.addLandmark(new LocateCamera.LandMark(new LocateCamera.Point(-60, 170), 2));
        lc.addLandmark(new LocateCamera.LandMark(new LocateCamera.Point(-85, 150), 3));

        
        lc.addDetectedTag(new LocateCamera.DetectedTag(0, 1.215160442));
        lc.addDetectedTag(new LocateCamera.DetectedTag(1, 1.570796327));
        lc.addDetectedTag(new LocateCamera.DetectedTag(2, 1.910088941));
        lc.addDetectedTag(new LocateCamera.DetectedTag(3, 2.086345334));
        
        ArrayList<LocateCamera.TrianglePair> result = lc.solve();

        LocateCamera.Point pAvg = new LocateCamera.Point(0, 0);
        LocateCamera.Point pBest = new LocateCamera.Point(0, 0);
        double sensitivity = Double.MAX_VALUE;
        for (int i = 0; i < result.size(); ++i) {
            LocateCamera.TrianglePair trp = result.get(i);
            pAvg.x += trp.observer.x;
            pAvg.y += trp.observer.y;
            if (trp.errorSensitivity < sensitivity) {
                sensitivity = trp.errorSensitivity;
                pBest = trp.observer;
            }
        }
        pAvg.x = pAvg.x / result.size();
        pAvg.y = pAvg.y / result.size();

        System.out.println("Average Position - X=" + pAvg.x + " Y=" + pAvg.y);
        System.out.println("Best Position - X=" + pBest.x + " Y=" + pBest.y);
       
        return;
    }

   
       
}